services:
  - type: web
    name: terra-accrete-prototype
    runtime: docker
    plan: free
    envVars:
      - key: RECIPIENT_EMAIL
        value: sheronmufunguri@gmail.com
      - key: FROM_EMAIL
        value: sheronmufunguri@gmail.com
      - key: SITE_NAME
        value: Terra-accrete Global
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: sheronmufunguri@gmail.com
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_ENCRYPTION
        value: tls
